const 
REG_USER = 'REG_USER',
REG_USER_ERROR = 'REG_USER_ERROR',
REG_USER_SUCCESS = 'REG_USER_SUCCESS',
FETCH_USER = 'FETCH_USER',
FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
FETCH_USER_ERROR = 'FETCH_USER_ERROR',
ADD_NEW_ITEM = 'ADD_NEW_ITEM',
ADD_NEW_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS',
ADD_NEW_ITEM_ERROR = 'ADD_NEW_ITEM_ERROR',
FETCH_USER_ITEMS = 'FETCH_USER_ITEMS',
DELETE_ITEM = 'DELETE_ITEM',
DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS',
DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export { 
    REG_USER, 
    REG_USER_ERROR, 
    REG_USER_SUCCESS, 
    FETCH_USER, 
    FETCH_USER_ERROR, 
    FETCH_USER_SUCCESS,
    ADD_NEW_ITEM,
    ADD_NEW_ITEM_SUCCESS,
    ADD_NEW_ITEM_ERROR,
    FETCH_USER_ITEMS,
    DELETE_ITEM,
    DELETE_ITEM_ERROR,
    DELETE_ITEM_SUCCESS
};